### ISSUE TITLE
Mostrar listado de restaurantes por zona extraído de un fichero (Hito - 20 de abril)

### ISSUE THREAD

**Issue by raquelcedazo** [aigora/twQ103_1920-twq103-appeteat#2]
Hola:

Os comento lo que veo de vuestra primera entrega y os propongo añadirle más funcionalidad.

El menú está bien para empezar, aunque el programa no debería terminar nunca hasta que el usuario indicara la opción de salir. 

El hito que os propongo para el 20 de abril es que creéis un fichero de texto (.txt) con todos los restaurantes con sus zonas correspondientes, lo leáis cuando arranque el programa y se muestre por pantalla cuando se pulse la opción correspondiente. Os aconsejo que almacenéis los datos en un vector de estructuras.

Además de esto, os animo a que sigáis programando más funcionalidades, como la de la gestión de usuarios, etc.

Un saludo y buenas vacaciones.

**Comment by aligutli** [comment]
Hola:

Estamos avanzando en el trabajo y nos han surgido varias dudas:

1)No entendemos muy bien la funcionalidad del fichero con todos los restaurantes.

2)Creemos que con la gestión de usuarios te refieres a que cuando se registren se guarden los en la "memoria" del programa y que haya opción de iniciar sesión una vez se haya registrado, pero nos gustaría que nos confirmases si te refieres a eso.

3)A la hora de subir el código más avanzado, ¿se sube en el mismo archivo de "Menú", o creamos otro distinto con otro nombre?

Muchas gracias.

**Comment by raquelcedazo** [comment]
Hola, os respondo a cada pregunta:
1) Me refiero a que toda la información de restaurantes que hay en el menú, se debería leer de un fichero, por ejemplo se me ocurre el siguiente formato donde el primer número es la zona y después el nombre:

1 Casa Primavera 
1 Ginos 
1 Goiko Grill
2 Foster's Hollywood
2 Tagliatella
2 Subway

2) Es eso, pero es una idea, podéis hacerlo o no.

3) Sí, sobre el mismo fichero, por tanto, deberías llamarle de una manera más intuitiva, por ejemplo, appeteat.c 

Un saludo
